# -*- coding: utf-8 -*-
"""Real Time Road Lane Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kYHoFYE_Raqk_9n9VGWLU97kG-iScPN

# 🚗 Lane Detection using OpenCV

This project detects lane lines in a road video using classical computer vision techniques:
- Edge Detection (Canny)
- Region of Interest Masking
- Hough Transform
- Lane Averaging

The output is a processed video with highlighted lane lines.
"""

!pip install moviepy

import numpy as np
import cv2
import moviepy.editor as editor

"""## Region of Interest Selection

This function masks the image to focus only on the road area.
"""

def region_selection(image):
    mask = np.zeros_like(image)

    if len(image.shape) > 2:
        ignore_mask_color = (255,) * image.shape[2]
    else:
        ignore_mask_color = 255

    rows, cols = image.shape[:2]

    bottom_left  = [cols * 0.1, rows * 0.95]
    top_left     = [cols * 0.4, rows * 0.6]
    bottom_right = [cols * 0.9, rows * 0.95]
    top_right    = [cols * 0.6, rows * 0.6]

    vertices = np.array([[bottom_left, top_left, top_right, bottom_right]], dtype=np.int32)

    cv2.fillPoly(mask, vertices, ignore_mask_color)
    return cv2.bitwise_and(image, mask)

"""## Hough Transform

Detects straight lines from edge-detected image.
"""

def hough_transform(image):
    return cv2.HoughLinesP(
        image,
        rho=1,
        theta=np.pi/180,
        threshold=20,
        minLineLength=20,
        maxLineGap=500
    )

"""## Lane Averaging

Separates left and right lanes and computes average slope & intercept.
"""

def average_slope_intercept(lines):
    if lines is None:
        return None, None

    left_lines, left_weights = [], []
    right_lines, right_weights = [], []

    for line in lines:
        for x1, y1, x2, y2 in line:
            if x1 == x2:
                continue

            slope = (y2 - y1) / (x2 - x1)
            intercept = y1 - slope * x1
            length = np.sqrt((y2 - y1)**2 + (x2 - x1)**2)

            if slope < 0:
                left_lines.append((slope, intercept))
                left_weights.append(length)
            else:
                right_lines.append((slope, intercept))
                right_weights.append(length)

    left_lane = None
    right_lane = None

    if len(left_weights) > 0:
        left_lane = np.dot(left_weights, left_lines) / np.sum(left_weights)

    if len(right_weights) > 0:
        right_lane = np.dot(right_weights, right_lines) / np.sum(right_weights)

    return left_lane, right_lane

"""## Convert Lines to Pixel Coordinates"""

def pixel_points(y1, y2, line):
    if line is None:
        return None

    slope, intercept = line

    if abs(slope) < 1e-3:  # safer check
        return None

    x1 = int((y1 - intercept) / slope)
    x2 = int((y2 - intercept) / slope)

    return ((x1, int(y1)), (x2, int(y2)))

"""## Construct Lane Lines"""

def lane_lines(image, lines):
    left_lane, right_lane = average_slope_intercept(lines)

    y1 = image.shape[0]
    y2 = int(y1 * 0.6)

    left_line = pixel_points(y1, y2, left_lane)
    right_line = pixel_points(y1, y2, right_lane)

    return [left_line, right_line]

"""## Draw Lane Lines on Frame"""

def draw_lane_lines(image, lines, color=[255, 0, 0], thickness=12):
    line_image = np.zeros_like(image)

    for line in lines:
        if line is not None:
            cv2.line(line_image, *line, color, thickness)

    return cv2.addWeighted(image, 1.0, line_image, 1.0, 0.0)

"""## Frame Processing Pipeline

Includes error handling to prevent freezing.
"""

def frame_processor(image):
    try:
        grayscale = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        blur = cv2.GaussianBlur(grayscale, (5, 5), 0)

        edges = cv2.Canny(blur, 50, 150)

        region = region_selection(edges)
        hough = hough_transform(region)

        if hough is None:
            return image

        lines = lane_lines(image, hough)

        return draw_lane_lines(image, lines)

    except Exception as e:
        print("Frame error:", e)
        return image

"""## Process Video

Includes:
- Resize for speed
- Subclip for testing
- Stable FPS output
"""

def process_video(input_path, output_path):
    video = editor.VideoFileClip(input_path).subclip(0, 10).resize(0.5)

    processed = video.fl_image(frame_processor)

    processed.write_videofile(output_path, fps=24, audio=False)

"""## Run Lane Detection"""

process_video('/content/test2.mp4', 'output.mp4')

"""## Output Video"""

from IPython.display import HTML
from base64 import b64encode

mp4 = open('output.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=500 controls>
    <source src="{data_url}" type="video/mp4">
</video>
""")